name: CI
#CI = Continuous Integration
#Think of the CI configuration file (this YAML file) as a nanny-style tutorial for GitHub bots
on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: lakehouse
          POSTGRES_USER: lakehouse
          POSTGRES_PASSWORD: lakehouse
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U lakehouse -d lakehouse"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    env:
      DB_HOST: 127.0.0.1
      DB_PORT: 5432
      DB_NAME: lakehouse
      DB_USER: lakehouse
      DB_PASSWORD: lakehouse

    steps:
      - uses: actions/checkout@v4

      - name: Setup (deps)
        run: |
          make setup

      - name: Lint
        run: |
          make lint

      - name: Migrate DB
        run: |
          make migrate

      - name: Smoke (DB)
        run: |
          make db-smoke

      - name: Run tests
        run: |
          make test